const TODOS_ITEM_CHANGE_ACTION = `TODOS_ITEM_CHANGE_ACTION`;
const TODOS_SORT_ACTION = `TODOS_SORT_ACTION`;
const TODOS_SET_ACTION = `TODOS_SET_ACTION`;

export { TODOS_ITEM_CHANGE_ACTION, TODOS_SORT_ACTION, TODOS_SET_ACTION };
