const SET_SORT_ACTION = `SET_SORT_ACTION`;
const SET_USERS_ACTION = `SET_USERS_ACTION`;
const SORT_USERS_ACTION = `SORT_USERS_ACTION`;

export { SET_SORT_ACTION, SET_USERS_ACTION, SORT_USERS_ACTION };
